language: python
python:
  - "3.8"
install:
  - pip install -r mysite/requirements.txt
script:
  - black --check mysite
  - flake8 mysite --exclude=migrations
  - pytest
  - coverage run --source=mysite mysite/manage.py test

after_script:
  - python -m coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "swe1-app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-135467027477"
  on:
    branch: master